### PR TITLE
Added OKHttpClient

### PR DESCRIPTION
**Pull request by costular**
I just added OkHttpClient as a different implementation. Now DefaultHttpClient is used by default (forgive the redundancy). 

However, maybe in the future would be interesting to select from a http client list based on user requirements. Here, OkHttp gives many benefits about performance.

### CODE REVIEW

**Comment by amitshekhariitbhu** [comment]
I think we should a separate module for the same in this project as `prdownloader-okHttp`.
@costular What is your thought on this?

**Comment by costular** [comment]
I agree with that. It makes sense in order to uncouple the http clients. Anyone could write another client and make a custom implementation easily. 

However, we should make some changes in _prdownloader_ core to avoid using always DefaultHttpClient.

**Comment by amitshekhariitbhu** [comment]
`PRDownloaderConfig` support passing custom HttpClient from outside.

**Comment by costular** [comment]
That's true, my bad. Then, I'll make some changes to move it to another module.

**Comment by Mustafa-Altameemi** [comment]
> I just added OkHttpClient as a different implementation. Now DefaultHttpClient is used by default (forgive the redundancy).
> 
> However, maybe in the future would be interesting to select from a http client list based on user requirements. Here, OkHttp gives many benefits about performance.

How can I use okhttp with PRDownloader now, please?

**Pull request closed without merging**
