### PR TITLE
Added downloadid parameter in download complete callback.

### PR DESCRIPTION
**Pull request by dpaksoni**
I have added a download id parameter in download complete callback.

### CODE REVIEW

**Comment by amitshekhariitbhu** [comment]
@dpaksoni Great that you are helping us here. If we do like this, when the old users upgrade, they will have to change the method signature. We need to think on the way of implementing this without breaking the older version.

**Comment by dpaksoni** [comment]
Thank you.
Yeah we can think of a way around this problem.

**Comment by dpaksoni** [comment]
Hi,
Did you think about it?

**Comment by amitshekhariitbhu** [comment]
We need to do this when we release a major update.

**Pull request closed without merging**
